name: NestJS CI/CD

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '15'
          postgresql db: 'nestjs_db'
          postgresql user: 'postgres'
          postgresql password: 'postgres'

      - name: Run database migrations
        run: npx prisma migrate deploy

      - name: Build NestJS application
        run: npm run build

      - name: Run tests
        run: npm run test:e2e