name: NestJS CI/CD (Alternative)

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create environment file
        run: |
          cp .env.example .env.docker
          echo "DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nestjs_db?schema=public" >> .env.docker

      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for database to be ready
        run: |
          docker compose exec -T postgres sh -c 'until pg_isready -U postgres; do sleep 1; done'

      - name: Run database migrations
        run: docker compose exec -T app npx prisma migrate deploy

      - name: Run unit tests
        run: docker compose exec -T app npm test

      - name: Run e2e tests
        run: docker compose exec -T app npm run test:e2e

      - name: Stop services
        if: always()
        run: docker compose down -v
